version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./migrations:/app/migrations
      - ./seeds:/app/seeds
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=200'

  app:
    build: .
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - db
