[features]
seeds = true
skip-lint = false
[programs.localnet]
mono_program = "Gu2VCpw4RagQ5gtxENrdXydPjyioEZqXgcyP2mf89xfA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chinedum/.config/solana/id.json"

[test]
startup_wait = 60000

[scripts]
test = "sh test.sh"
