[features]
seeds = true
skip-lint = false
[programs.devnet]
mono_program = "LnCrQyE83MgFTT8XftEMxzZedEbYx7ishUQ5ytA7pyk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jacksturtevant/.config/solana/id.json"

[test]
startup_wait = 60000

[scripts]
test = "sh test.sh"
